### ISSUE TITLE
nnet packages vs. self-implemented nnets

### ISSUE THREAD

**Issue by hyiltiz** [galbiati/nns-for-mnk#3]
Strictly speaking, this is not an issue but why not discuss it here. There are quite a few nnet packages out there for any popular programming platform/language. Also, implementing neural networks such as the ones we usually use for our science projects are ones that are simple and tractable ones rather than those deep recurrent/convolutional nnets. A practical question: what do you think is the benefit of using a third-party library for implementing simple nnets as opposed to directly implementing those from scratch?

**Comment by galbiati** [comment]
As long as the nnets you're using really are quite simple, there's probably not much advantage either way.

However, I'm actually using moderately complicated architectures, including convolutional layers, and I've found Lasagne's layers abstraction and updates algos (eg adagrad) really useful. Inheriting from base classes is really convenient for custom operations, as is the ability to cut back into the network to get eg outputs from individual layers. It means a lot less time spent on details, which helps when I want to try 50+ different architectures. I'd say it's probably saved me substantial development time.

Mostly can't speak to other packages as I haven't tried.

**Comment by hyiltiz** [comment]
Thanks for sharing the experience. I think it would be better for me to first check out what you did then decide myself based on the complexity. I am essentially just modeling a single layer recurrent network with neurons that have gaussian tuning curves. Not sure where it lies on the complexity axis.
